python train.py --method HGNN --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method HGNN --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method HGNN --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method HGNN --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method HGNN --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9
python train.py --method HGNN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method HGNN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method HGNN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method HGNN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method HGNN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9

python train.py --method AllDeepSets --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method AllDeepSets --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method AllDeepSets --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method AllDeepSets --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method AllDeepSets --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9
python train.py --method AllDeepSets --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method AllDeepSets --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method AllDeepSets --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method AllDeepSets --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method AllDeepSets --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9

python train.py --method AllSetTransformer --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method AllSetTransformer --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method AllSetTransformer --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method AllSetTransformer --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method AllSetTransformer --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.9
python train.py --method AllSetTransformer --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method AllSetTransformer --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method AllSetTransformer --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method AllSetTransformer --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method AllSetTransformer --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.9

python train.py --method HyperGCN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.00001 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.01 --perturb_type replace --perturb_prop 0.1
python train.py --method HyperGCN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.00001 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.01 --perturb_type replace --perturb_prop 0.3
python train.py --method HyperGCN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.00001 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.01 --perturb_type replace --perturb_prop 0.5
python train.py --method HyperGCN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.00001 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.01 --perturb_type replace --perturb_prop 0.7
python train.py --method HyperGCN --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.00001 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.01 --perturb_type replace --perturb_prop 0.9
python train.py --method HyperGCN --dname cora --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.0 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method HyperGCN --dname cora --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.0 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method HyperGCN --dname cora --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.0 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method HyperGCN --dname cora --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.0 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method HyperGCN --dname cora --All_num_layers 1 --MLP_num_layers 2 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 64 --HyperGCN_mediators --HyperGCN_fast --wd 0.0 --epochs 500 --runs 20 --feature_noise 0.0 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9

python train.py --method HCHA --HCHA_symdegnorm --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method HCHA --HCHA_symdegnorm --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method HCHA --HCHA_symdegnorm --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method HCHA --HCHA_symdegnorm --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method HCHA --HCHA_symdegnorm --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 4 --lr 0.001 --perturb_type replace --perturb_prop 0.9
python train.py --method HCHA --HCHA_symdegnorm --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 5 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method HCHA --HCHA_symdegnorm --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 5 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method HCHA --HCHA_symdegnorm --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 5 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method HCHA --HCHA_symdegnorm --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 5 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method HCHA --HCHA_symdegnorm --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 20 --cuda 5 --lr 0.001 --perturb_type replace --perturb_prop 0.9

python train.py --method UniGCNII --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method UniGCNII --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method UniGCNII --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method UniGCNII --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method UniGCNII --dname cora --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9
python train.py --method UniGCNII --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.1
python train.py --method UniGCNII --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.3
python train.py --method UniGCNII --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.5
python train.py --method UniGCNII --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.7
python train.py --method UniGCNII --dname coauthor_dblp --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 20 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0.9

